# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab4af751dc9d14da28199ecc9f762bf3a61de2c80725c2d7bf30bc1ce622384b051222cbfeffff3e9b18ad1af5876bca525eea0c42e68d1073466f8287a4e65b

test:
  secret_key_base: e0ba2a1b1a6c99f650b3d56ba601a546af15331020c01ea02b96ed42700bbb40b27b30daffb553ba236296a45e0b5a8e855509e81c8437346b3c03fe1f61e2c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
